// userFoodLog.js
export const tableData = [
  { food: "Oatmeal with Almonds & Banana", calories: 310, protein: "9g", carbs: "45g", fat: "10g" },
  { food: "Scrambled Eggs with Spinach", calories: 220, protein: "14g", carbs: "3g", fat: "16g" },
  { food: "Greek Yogurt with Honey & Berries", calories: 180, protein: "12g", carbs: "22g", fat: "4g" },
  { food: "Grilled Chicken Salad (olive oil dressing)", calories: 320, protein: "30g", carbs: "8g", fat: "18g" },
  { food: "Avocado Toast (whole grain)", calories: 250, protein: "7g", carbs: "28g", fat: "12g" },
  { food: "Apple Juice (200ml)", calories: 90, protein: "0.2g", carbs: "22g", fat: "0g" },
  { food: "Brown Rice & Lentil Bowl", calories: 380, protein: "16g", carbs: "60g", fat: "6g" },
  { food: "Peanut Butter Sandwich", calories: 340, protein: "13g", carbs: "32g", fat: "18g" },
  { food: "Salmon with Steamed Broccoli", calories: 410, protein: "34g", carbs: "6g", fat: "24g" },
  { food: "Mixed Fruit Salad", calories: 140, protein: "2g", carbs: "34g", fat: "0.5g" },
  { food: "Vegetable Soup (clear broth)", calories: 90, protein: "4g", carbs: "14g", fat: "2g" },
  { food: "Paneer Stir Fry with Veggies", calories: 360, protein: "20g", carbs: "15g", fat: "25g" },
  { food: "Quinoa Chickpea Bowl", calories: 420, protein: "18g", carbs: "58g", fat: "10g" },
  { food: "Mango Smoothie (low fat milk)", calories: 210, protein: "6g", carbs: "35g", fat: "4g" },
  { food: "Boiled Eggs (2 pcs)", calories: 140, protein: "12g", carbs: "1g", fat: "9g" },
  { food: "Tuna Sandwich", calories: 330, protein: "26g", carbs: "28g", fat: "12g" },
  { food: "Chicken Curry with Brown Rice", calories: 520, protein: "35g", carbs: "55g", fat: "16g" },
  { food: "Cucumber Mint Detox Water", calories: 15, protein: "0g", carbs: "3g", fat: "0g" },
  { food: "Cheese Omelette", calories: 290, protein: "17g", carbs: "2g", fat: "24g" },
  { food: "Grilled Paneer Wrap", calories: 410, protein: "22g", carbs: "35g", fat: "18g" },
  { food: "Protein Shake (whey, banana, milk)", calories: 280, protein: "25g", carbs: "25g", fat: "6g" },
  { food: "Green Smoothie (spinach, apple, cucumber)", calories: 130, protein: "3g", carbs: "26g", fat: "1g" },
  { food: "Veggie Pasta (olive oil & herbs)", calories: 460, protein: "15g", carbs: "68g", fat: "12g" },
  { food: "Fresh Orange Juice (250ml)", calories: 110, protein: "1.5g", carbs: "26g", fat: "0g" },
];
